/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

public void button1_click1(GButton source, GEvent event) { //_CODE_:button1:605786:
  speechCount = 0;

  Jeff.causeDisturbance(1);
  //delay(5000);
} //_CODE_:button1:605786:

public void button2_click1(GButton source, GEvent event) { //_CODE_:button2:472636:
  speechCount = 0;

   Jeff.askQuestion(1);
} //_CODE_:button2:472636:

public void button3_click1(GButton source, GEvent event) { //_CODE_:button3:760748:
  speechCount = 0;

  Snatty.speak();
} //_CODE_:button3:760748:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  button1 = new GButton(this, 103, 31, 80, 30);
  button1.setText("Disturbance");
  button1.addEventHandler(this, "button1_click1");
  button2 = new GButton(this, 101, 81, 80, 30);
  button2.setText("Question");
  button2.addEventHandler(this, "button2_click1");
  button3 = new GButton(this, 102, 129, 80, 30);
  button3.setText("Answer");
  button3.addEventHandler(this, "button3_click1");
}

// Variable declarations 
// autogenerated do not edit
GButton button1; 
GButton button2; 
GButton button3; 
